/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : IFsh1.c
**     Project     : kea-pump
**     Processor   : SKEAZ128MLK4
**     Component   : IntFLASH
**     Version     : Component 02.409, Driver 01.02, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-10-13, 18:36, # CodeGen: 11
**     Abstract    :
**         This component "IntFLASH" implements an access to internal FLASH.
**         The component support reading/writing data into FLASH, erasing of
**         selected sector.
**         The component supports events if the write interrupt is supported.
**         The component supports following modes of write operations:
**           - Write - writing without any test.
**           - Destructive write - sector is erased if necessary.
**           - Safe write - user event is invoked to save and resore data
**                          from the current sector.
**         The component requires on-chip FLASH memory (not used/allocated by
**         other components).
**     Settings    :
**          Component name                                 : IFsh1
**          FLASH                                          : FTMRE
**          FLASH_LDD                                      : FLASH_LDD
**          Write method                                   : Write
**          Interrupt service/event                        : Enabled
**            Command complete interrupt                   : 
**              Interrupt                                  : INT_FTMRE
**              Interrupt priority                         : medium priority
**          Wait in RAM                                    : yes
**          Virtual page                                   : Enabled
**            Allocated                                    : By the component
**            Page size                                    : 2048
**          Initialization                                 : 
**            Events enabled in init.                      : yes
**            Wait enabled in init.                        : yes
**          CPU clock/speed selection                      : 
**            FLASH clock                                  : 
**            High speed mode                              : This component enabled
**            Low speed mode                               : This component disabled
**            Slow speed mode                              : This component disabled
**     Contents    :
**         DisableEvent - byte IFsh1_DisableEvent(void);
**         EnableEvent  - byte IFsh1_EnableEvent(void);
**         EraseSector  - byte IFsh1_EraseSector(IFsh1_TAddress Addr);
**         SetByteFlash - byte IFsh1_SetByteFlash(IFsh1_TAddress Addr, byte Data);
**         GetByteFlash - byte IFsh1_GetByteFlash(IFsh1_TAddress Addr, byte *Data);
**         SetBytePage  - byte IFsh1_SetBytePage(word Index, byte Data);
**         SetWordPage  - byte IFsh1_SetWordPage(word Index, word Data);
**         GetBytePage  - byte IFsh1_GetBytePage(word Index, byte *Data);
**         GetWordPage  - byte IFsh1_GetWordPage(word Index, word *Data);
**         SetPage      - byte IFsh1_SetPage(IFsh1_TAddress Addr);
**         GetPage      - byte IFsh1_GetPage(IFsh1_TAddress Addr);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file IFsh1.c
** @version 01.02
** @brief
**         This component "IntFLASH" implements an access to internal FLASH.
**         The component support reading/writing data into FLASH, erasing of
**         selected sector.
**         The component supports events if the write interrupt is supported.
**         The component supports following modes of write operations:
**           - Write - writing without any test.
**           - Destructive write - sector is erased if necessary.
**           - Safe write - user event is invoked to save and resore data
**                          from the current sector.
**         The component requires on-chip FLASH memory (not used/allocated by
**         other components).
*/         
/*!
**  @addtogroup IFsh1_module IFsh1 module documentation
**  @{
*/         

/* MODULE IFsh1. */

#include "Events.h"
#include "IFsh1.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Internal method prototypes */

#define IFsh1_TOTAL_FLASH_BLOCK_COUNT  0x01U
#define IFsh1_P_FLASH_SIZE             0x00020000U
#define IFsh1_P_FLASH_BLOCK_COUNT      0x01U
#define IFsh1_P_FLASH_BLOCK_SIZE       0x00020000U

#define IFsh1_CMD_NONE                 0x00U
#define IFsh1_CMD_READ                 0x01U
#define IFsh1_CMD_ERASE_SECTOR         0x02U
#define IFsh1_CMD_ERASE_BLOCK          0x03U
#define IFsh1_CMD_VERIFY_ERASED_BLOCK  0x04U
#define IFsh1_CMD_WRITE                0x05U
#define IFsh1_CMD_WRITE_ERASE          0x06U

typedef struct IFsh1_TSector_Struct {
  uint32_t Data[IntFlashLdd1_FLASH_ERASABLE_UNIT_SIZE/4U];
} IFsh1_TSector;

static uint32_t IFsh1_CurrentCommand;  /* Current command */
static bool IFsh1_CmdResult;           /* Last command result */
static bool IFsh1_CmdPending;          /* Current command state */
static bool IFsh1_EnEvent;             /* State of events (enabled/disabled) */

static LDD_TDeviceData* IntFlashLdd1_DevDataPtr;
static byte IFsh1_Page[IFsh1_VIRTUAL_PAGE_SIZE];
static byte IFsh1_PgEvent;             /* Anticipate event */

byte IFsh1_GetFlash(LDD_FLASH_TAddress Source, LDD_TData *Dest, LDD_FLASH_TDataSize Count);
byte IFsh1_SetFlash(IFsh1_TDataAddress Source, IFsh1_TAddress Dest, word Count);

/*
** ===================================================================
**     Method      :  IFsh1_GetFlash (component IntFLASH)
**
**     Description :
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
byte IFsh1_GetFlash(LDD_FLASH_TAddress Source, LDD_TData *Dest, LDD_FLASH_TDataSize Count)
{
  LDD_TError                 Result;
  
  if (IFsh1_CmdPending) {
    return ERR_BUSY;
  }
  IFsh1_CurrentCommand = IFsh1_CMD_READ;
  IFsh1_CmdPending = TRUE;
  Result = IntFlashLdd1_Read(IntFlashLdd1_DevDataPtr, Source,  Dest,  Count); /* Start reading from the flash memory */
  if (Result == ERR_OK) {              /* Command accepted? */
    do {
      IntFlashLdd1_Main(IntFlashLdd1_DevDataPtr);
    } while (IFsh1_CmdPending);
    Result = IFsh1_CmdResult;
  } else if (Result == ERR_PARAM_ADDRESS) {
    IFsh1_CmdPending = FALSE;
    Result = ERR_RANGE;
  } else {
  }
  return (byte)Result;
}

/*
** ===================================================================
**     Method      :  IFsh1_SetFlash (component IntFLASH)
**
**     Description :
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
byte IFsh1_SetFlash(IFsh1_TDataAddress Src, IFsh1_TAddress Dst, word Count)
{
  LDD_TError                 Result;

  if (IFsh1_CmdPending) {
    return ERR_BUSY;
  }
  IFsh1_CurrentCommand = IFsh1_CMD_WRITE;
  IFsh1_CmdPending = TRUE;
  Result = IntFlashLdd1_Write(IntFlashLdd1_DevDataPtr, (LDD_TData *)Src, Dst, (LDD_FLASH_TDataSize)Count); /* Start reading from the flash memory */
  if (Result == ERR_OK) {
    do {
    } while (IFsh1_CmdPending);
    Result = IFsh1_CmdResult;
  } else {
    IFsh1_CmdPending = FALSE;          /* Command parameter error */
    if (Result == ERR_PARAM_ADDRESS) {
      Result = ERR_RANGE;
    }
  }
  return (byte)Result;
}

/*
** ===================================================================
**     Method      :  IFsh1_Init (component IntFLASH)
**
**     Description :
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void IFsh1_Init(void)
{
  IntFlashLdd1_DevDataPtr = IntFlashLdd1_Init(NULL);
  IFsh1_PgEvent = 0U;                  /* No events expected */
  IFsh1_CmdPending = FALSE;
  IFsh1_EnEvent = TRUE;                /* Remember events state */
}

/*
** ===================================================================
**     Method      :  IFsh1_DisableEvent (component IntFLASH)
*/
/*!
**     @brief
**         This method disables all the events except [OnSaveBuffer],
**         [OnRestoreBuffer] and [OnEraseError]. The method is
**         available only if any event is enabled.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_SPEED - This device does not work in
**                           the active speed mode
*/
/* ===================================================================*/
byte IFsh1_DisableEvent(void)
{
  IFsh1_EnEvent = FALSE;
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  IFsh1_EnableEvent (component IntFLASH)
*/
/*!
**     @brief
**         This method enables all the events except [OnSaveBuffer],
**         [OnRestoreBuffer] and [OnEraseError]. The method is
**         available only if any event is enabled.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_SPEED - This device does not work in
**                           the active speed mode
*/
/* ===================================================================*/
byte IFsh1_EnableEvent(void)
{
  IFsh1_EnEvent = TRUE;
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  IFsh1_EraseSector (component IntFLASH)
*/
/*!
**     @brief
**         Erases the sector to which address Addr belongs.
**     @param
**         Addr            - Address in FLASH.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_NOTAVAIL - Desired program/erase
**                           operation is not available 
**                           - ERR_RANGE - Address is out of range 
**                           - ERR_SPEED - This device does not work in
**                           the active speed mode 
**                           - ERR_BUSY - Device is busy 
**                           - ERR_PROTECT - Flash is write protect 
**                           - ERR_VALUE - Flash sector erase was not
**                           successful
*/
/* ===================================================================*/
byte IFsh1_EraseSector(IFsh1_TAddress Addr)
{
  LDD_TError                 Result;

  if (IFsh1_CmdPending) {
    return ERR_BUSY;
  }
  IFsh1_CurrentCommand = IFsh1_CMD_ERASE_SECTOR;
  IFsh1_CmdPending = TRUE;
  Result = IntFlashLdd1_Erase(IntFlashLdd1_DevDataPtr, (LDD_FLASH_TAddress)Addr, 1U);
  if (Result == ERR_OK) {
    do {
    } while (IFsh1_CmdPending);
    Result = IFsh1_CmdResult;
  } else {
    IFsh1_CmdPending = FALSE;          /* Command parameter error */
    if (Result == ERR_PARAM_ADDRESS) {
      Result = ERR_RANGE;
    }
  }
  return (byte)Result;
}

/*
** ===================================================================
**     Method      :  IFsh1_SetByteFlash (component IntFLASH)
*/
/*!
**     @brief
**         Writes a byte to an address in FLASH. The operation of this
**         method depends on the "Write method" property and state of
**         the flash. Please see more details on general info page of
**         the help.
**     @param
**         Addr            - Address to FLASH.
**     @param
**         Data            - Data to write.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_NOTAVAIL - Desired program/erase
**                           operation is not available 
**                           - ERR_RANGE - Address is out of range 
**                           - ERR_VALUE - Read value is not equal to
**                           written value 
**                           - ERR_SPEED - This device does not work in
**                           the active speed mode 
**                           - ERR_BUSY - Device is busy 
**                           - ERR_PROTECT - Flash is write protect
*/
/* ===================================================================*/
byte IFsh1_SetByteFlash(IFsh1_TAddress Addr, byte Data)
{
  return IFsh1_SetFlash((IFsh1_TDataAddress)(void*)&Data, Addr,1U);
}

/*
** ===================================================================
**     Method      :  IFsh1_GetByteFlash (component IntFLASH)
*/
/*!
**     @brief
**         Gets byte from an address in FLASH.
**     @param
**         Addr            - Address to FLASH.
**     @param
**         Data            - A pointer to the returned 8-bit data.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_RANGE - Address is out of range 
**                           - ERR_BUSY - Device is busy
*/
/* ===================================================================*/
byte IFsh1_GetByteFlash(IFsh1_TAddress Addr, byte *Data)
{
  return(IFsh1_GetFlash((LDD_FLASH_TAddress)Addr,(LDD_TData*)Data,(LDD_FLASH_TDataSize)1U));
}

/*
** ===================================================================
**     Method      :  IFsh1_SetBytePage (component IntFLASH)
*/
/*!
**     @brief
**         Writes a byte to an address of the virtual page. This method
**         is only available when [Virtual page] property is enabled.
**     @param
**         Index           - Index to virtual page.
**     @param
**         Data            - Data to write.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_RANGE - Index is out of range 
**                           - ERR_NOTAVAIL - Virtual page address not
**                           set by the user
*/
/* ===================================================================*/
byte IFsh1_SetBytePage(word Index, byte Data)
{
  if (Index < IFsh1_VIRTUAL_PAGE_SIZE) {
    IFsh1_Page[Index] = Data;
    return ERR_OK;
  } else {
    return ERR_RANGE;
  }
}

/*
** ===================================================================
**     Method      :  IFsh1_SetWordPage (component IntFLASH)
*/
/*!
**     @brief
**         Writes a word to an address in the virtual page. This method
**         is only available when [Virtual page] property is enabled.
**     @param
**         Index           - Index to virtual page.
**     @param
**         Data            - Data to write.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_RANGE - Index is out of range
**                           - ERR_NOTAVAIL - Virtual page address not
**                           set by the user
*/
/* ===================================================================*/
byte IFsh1_SetWordPage(word Index, word Data)
{
  if (Index < (IFsh1_VIRTUAL_PAGE_SIZE - 1U)) {
    *(word *)&IFsh1_Page[Index] = Data;
    return ERR_OK;
  } else {
    return ERR_RANGE;
  }
}

/*
** ===================================================================
**     Method      :  IFsh1_GetBytePage (component IntFLASH)
*/
/*!
**     @brief
**         Gets a byte from an address in the virtual page. This method
**         is only available when [Virtual page] property is enabled.
**     @param
**         Index           - Index to a virtual page.
**     @param
**         Data            - A pointer to the returned 8-bit data.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_RANGE - Index is out of range
**                           - ERR_NOTAVAIL - Virtual page address not
**                           set by the user
*/
/* ===================================================================*/
byte IFsh1_GetBytePage(word Index, byte *Data)
{
  if (Index < IFsh1_VIRTUAL_PAGE_SIZE) {
    *Data = IFsh1_Page[Index];
    return ERR_OK;
  } else {
    return ERR_RANGE;
  }
}

/*
** ===================================================================
**     Method      :  IFsh1_GetWordPage (component IntFLASH)
*/
/*!
**     @brief
**         Gets a word from an address in the virtual page. This method
**         is only available when [Virtual page] property is enabled.
**     @param
**         Index           - Index to virtual page.
**     @param
**         Data            - A pointer to the returned 16-bit data.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_RANGE - Index is out of range 
**                           - ERR_NOTAVAIL - Virtual page address not
**                           set by the user
*/
/* ===================================================================*/
byte IFsh1_GetWordPage(word Index, word *Data)
{
  if (Index < (IFsh1_VIRTUAL_PAGE_SIZE - 1U)) {
    *Data = *(word *)&IFsh1_Page[Index];
    return ERR_OK;
  } else {
    return ERR_RANGE;
  }
}

/*
** ===================================================================
**     Method      :  IFsh1_SetPage (component IntFLASH)
*/
/*!
**     @brief
**         Writes a virtual page to an address in FLASH. This method is
**         enabled only if [Virtual page] property is enabled. The
**         operation of this method depends on the "Write method"
**         property and state of the flash. Please see more details on
**         general info page of the help.
**     @param
**         Addr            - Address in FLASH.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_NOTAVAIL - Desired program/erase
**                           operation is not available 
**                           - ERR_RANGE - The address is out of range 
**                           - ERR_VALUE - The read value is not equal
**                           to the written value 
**                           - ERR_SPEED - This device does not work in
**                           the active speed mode 
**                           - ERR_BUSY - Device is busy 
**                           - ERR_PROTECT - Flash is write protect
*/
/* ===================================================================*/
byte IFsh1_SetPage(IFsh1_TAddress Addr)
{
  IFsh1_PgEvent = 1U;                  /* OnPageWriteEnd events expected */
  return IFsh1_SetFlash((IFsh1_TDataAddress)&IFsh1_Page, Addr, (LDD_FLASH_TDataSize)IFsh1_VIRTUAL_PAGE_SIZE);
}

/*
** ===================================================================
**     Method      :  IFsh1_GetPage (component IntFLASH)
*/
/*!
**     @brief
**         Gets the virtual page from FLASH. This method is enabled
**         only if [Virtual page] property is enabled.
**     @param
**         Addr            - Address in FLASH.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_RANGE - The address is out of range 
**                           - ERR_BUSY - Device is busy
*/
/* ===================================================================*/
byte IFsh1_GetPage(IFsh1_TAddress Addr)
{
  return(IFsh1_GetFlash(Addr,(LDD_TData *)&IFsh1_Page,(LDD_FLASH_TDataSize)IFsh1_VIRTUAL_PAGE_SIZE));
}

/*
** ===================================================================
**     Method      :  IFsh1_OnOperationComplete (component IntFLASH)
**
**     Description :
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void IntFlashLdd1_OnOperationComplete(LDD_TUserData *UserDataPtr)
{
  (void)UserDataPtr;                   /* Parameter is not used, suppress unused argument warning */
  IFsh1_CmdResult = ERR_OK;            /* No error appears */
  switch (IFsh1_CurrentCommand) {
    case IFsh1_CMD_WRITE:
      IFsh1_CmdPending = FALSE;        /* Command is finished */
      break;
    default:
      IFsh1_CmdPending = FALSE;        /* Command is finished */
      return;
  }
  if (IFsh1_EnEvent == TRUE) {
    if (IFsh1_PgEvent == 1U) {         /* OnPageWriteEnd events expected */
      IFsh1_PgEvent = 0U;
      IFsh1_OnWritePageEnd();
    } else {
      IFsh1_OnWriteEnd();
    }
  }
}

/*
** ===================================================================
**     Method      :  IFsh1_OnError (component IntFLASH)
**
**     Description :
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void IntFlashLdd1_OnError(LDD_TUserData *UserDataPtr)
{
  LDD_FLASH_TErrorStatus FLASH_LDD_ErrorStatus;

  (void)UserDataPtr;                   /* Parameter is not used, suppress unused argument warning */
  IFsh1_CmdPending = FALSE;
  IFsh1_CurrentCommand = IFsh1_CMD_NONE;
  IntFlashLdd1_GetError(IntFlashLdd1_DevDataPtr, &FLASH_LDD_ErrorStatus);
  if (FLASH_LDD_ErrorStatus.CurrentErrorFlags & LDD_FLASH_PROTECTION_VIOLATION) {
    IFsh1_CmdResult = ERR_PROTECT;     /* Protection violation */
  } else {
    IFsh1_CmdResult = ERR_VALUE;       /* Access error or Read collision error */
  }
}

/* END IFsh1. */

#ifdef __cplusplus
}  /* extern "C" */
#endif

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
